services:
  - docker

jobs:
  include:
    - env: OCAML_VERSION=4.12.0 UNISON_VERSION=2.51.3
    - env: OCAML_VERSION=4.12.0 UNISON_VERSION=2.51.4_rc2

before_install:
  - docker buildx create --use

script: docker buildx build
    --platform linux/amd64,linux/arm64
    --build-arg OCAML_VERSION=$OCAML_VERSION
    --build-arg UNISON_VERSION=$UNISON_VERSION
    --tag eugenmayer/unison:$UNISON_VERSION-$OCAML_VERSION .
#     .

# deploy:
#   provider: script
#   script: bash docker_push.sh
#   on:
#     branch: master
